jobs:
- job: myjob
  displayName: MyJob
  pool:
    name: 'Default'
  steps:
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      version: 'v3.11.0'
      cmd: 'oc new-app https://github.com/lstocchi/nodejs-ex -l name=demoapp'
      uselocalOc: true
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc status'
      uselocalOc: true

  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc get pods'
      uselocalOc: true
  
