# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  name: 'default'
  
steps:
- task: oc-setup@2
  inputs:
    openshiftService: 'My Openshift'
    version: 'v3.11.0'

