jobs:
- job: myjob
  displayName: MyJob
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: CmdLine@2
    inputs:
      script: 'ls ${SYSTEM_DEFAULTWORKINGDIRECTORY}'
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc version'
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc get pods'