# -----------------------------------------------------------------------------------------------
#  Copyright (c) Red Hat, Inc. All rights reserved.
#  Licensed under the MIT License. See LICENSE file in the project root for license information.
# ----------------------------------------------------------------------------------------------- 
jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm install -g tfx-cli typescript json del-cli copy-node-modules markserv ts-mocha mocha mocha-junit-reporter
        displayName: 'npm run setup, install, run build'
      - script: |
          npm install
        displayName: 'npm install'
      - script: |
          npm run build
        displayName: 'npm run build'
      - script: |
          ts-mocha -p tsconfig.json test/*-test.ts --timeout 5000 ${MOCHA_TAG} "--reporter" "mocha-junit-reporter" "--reporter-options" "mochaFile=out/test-report.xml"
        displayName: 'Run tests'  
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-report.xml'
          testRunTitle: 'Test results'  
      - script: npm run prettier:check
        displayName: Syntax check
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm install -g tfx-cli typescript json del-cli copy-node-modules markserv ts-mocha mocha mocha-junit-reporter
        displayName: 'npm run setup, install, run build'
      - script: |
          npm install
        displayName: 'npm install'
      - script: |
          npm run build
        displayName: 'npm run build'
      - script: |
          ts-mocha -p tsconfig.json test/*-test.ts --timeout 5000 ${MOCHA_TAG} "--reporter" "mocha-junit-reporter" "--reporter-options" "mochaFile=out/test-report.xml"
        displayName: 'Run tests'  
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-report.xml'
          testRunTitle: 'Test results'  
      - script: npm run prettier:check
        displayName: Syntax check
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm install -g tfx-cli typescript json del-cli copy-node-modules markserv ts-mocha mocha mocha-junit-reporter
        displayName: 'npm run setup, install, run build'
      - script: |
          npm install
        displayName: 'npm install'
      - script: |
          npm run build
        displayName: 'npm run build'
      - script: |
          ts-mocha -p tsconfig.json test/*-test.ts --timeout 5000 ${MOCHA_TAG} "--reporter" "mocha-junit-reporter" "--reporter-options" "mochaFile=out/test-report.xml"
        displayName: 'Run tests'  
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-report.xml'
          testRunTitle: 'Test results'  
      - script: npm run prettier:check
        displayName: Syntax check