jobs:
- job: myjob
  displayName: MyJob
  pool:
    name: 'Default'
  steps:
    - task: oc-cmd@2
      inputs:
        openshiftService: 'My Openshift'
        version: '4.1'
        cmd: 'oc version'
    - task: oc-cmd@2
      inputs:
        openshiftService: 'My Openshift'
        version: '4.2'
        cmd: 'oc get pods'
  