# Build NodeJS Express app using Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  name: 'WindowsLocal'
  
steps:
- checkout: self
  persistCredentials: true

- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    version: 'v3.11.0'
    cmd: 'oc get pods'
    uselocalOc: true