# Build NodeJS Express app using Azure Pipelines

# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'ubuntu-16.04'
  
steps:
- checkout: none
  persistCredentials: true

- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    version: 'v3.11.0'
    cmd: 'oc delete pod hello'
    ignoreFlag: true
