# Build NodeJS Express app using Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- checkout: self
  persistCredentials: true

jobs:
  - job: CacheBeta@0
    inputs:
      key: '*.tar.gz'
      path: $(System.DefaultWorkingDirectory) + '/.download/'
  
  - job: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      version: 'v3.11.0'
      cmd: 'oc version'