# Build NodeJS Express app using Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  name: 'Default'
  
steps:
- checkout: self
  persistCredentials: true

- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    cmd: 'oc get pods'
    uselocalOc: true