# Build NodeJS Express app using Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- checkout: self
  persistCredentials: true

- task: RestoreAndSaveCache@1
  inputs:
    keyfile: 'openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit'
    targetfolder: '/home/vsts/work/1/s/.download'
    vstsFeed: '810871f4-3187-4e04-9f85-5d6982a14872'
    
- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    version: 'v3.11.0'
    cmd: 'oc version'