# Build NodeJS Express app using Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
stages:
  - stage: Openshift
    jobs:
      - job: Build
        pool: 
          vmImage: 'Ubuntu 16.04'
        continueOnError: true
        steps:
          - task: oc-cmd@2
            inputs:
              openshiftService: 'My Openshift'
              version: 'v3.11.0'
              cmd: 'oc version'

