jobs:
- job: myjob
  displayName: MyJob
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      version: 'https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.1/windows/oc.zip'
      cmd: 'oc version'