jobs:
- job: myjob
  displayName: MyJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      version: 'v3.11.154'
      cmd: 'oc version'