jobs:
- job: myjob
  displayName: MyJob
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        cd "$(dirname -- "./.rsp")"
        
        dir="$PWD"
        
        echo "$dir"
        
        cd - > /dev/null
  