jobs:
- job: myjob
  displayName: MyJob
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      version: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.2/openshift-client-windows-4.2.2.zip'
      cmd: 'oc version'