 
# -----------------------------------------------------------------------------------------------
#  Copyright (c) Red Hat, Inc. All rights reserved.
#  Licensed under the MIT License. See LICENSE file in the project root for license information.
# ----------------------------------------------------------------------------------------------- 
jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm run setup
          npm install
          npm run build
        displayName: 'npm run setup, install, run build'
      - script: |
          npm run test:report:ci
        displayName: 'Run tests'  
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-report.xml'
          testRunTitle: 'Test results'  
      - script: npm run prettier:check
        displayName: Syntax check
      - script: npm run extension:version:set
        displayName: Set release version
        condition: eq(variables['release'], 'true')
      - script: npm run extension:create:dev
        displayName: Build extension
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm run setup
          npm install
          npm run build
        displayName: 'npm run setup, install, run build'
      - script: |
          npm run test:report:ci
        displayName: 'Run tests'  
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-report.xml'
          testRunTitle: 'Test results'  
      - script: npm run prettier:check
        displayName: Syntax check
      - script: npm run extension:version:set
        displayName: Set release version
        condition: eq(variables['release'], 'true')
      - script: npm run extension:create:dev
        displayName: Build extension
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm run setup
          npm install
          npm run build
        displayName: 'npm run setup, install, run build'
      - script: |
          npm run test:report:ci
        displayName: 'Run tests'  
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-report.xml'
          testRunTitle: 'Test results'  
      - script: npm run prettier:check
        displayName: Syntax check
      - script: npm run extension:version:set
        displayName: Set release version
        condition: eq(variables['release'], 'true')
      - script: npm run extension:create:dev
        displayName: Build extension