jobs:
- job: myjob
  displayName: MyJob
  pool:
    vmImage: 'Ubuntu-latest'
  steps:
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc version'
      uselocalOc: true
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc get pods'
      uselocalOc: true