jobs:
- job: myjob
  displayName: MyJob
  pool:
    name: 'Default'
  steps:
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      version: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.2/openshift-client-linux-4.2.2.tar.gz'
      cmd: 'oc version'