jobs:
- job: myjob
  displayName: MyJob
  pool:
    name: 'Default'
  steps:
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc version'
  - task: oc-cmd@2
    inputs:
      openshiftService: 'My Openshift'
      cmd: 'oc get pods'