# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- checkout: none
  persistCredentials: true

- task: oc-list-cmds@2
  inputs:
    openshiftService: 'My Openshift'
    version: 'v3.11.0'
    cmds: 'oc version

          oc get pods
          
          oc get dc'

