# Build NodeJS Express app using Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.16.0
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm run setup
          npm install
          npm run build
        displayName: 'npm run setup, install, run build'
      - script: |
          ts-mocha -p tsconfig.json test/*-test.ts --timeout 5000 ${MOCHA_TAG} "--reporter" "mocha-junit-reporter" "--reporter-options" "mochaFile=out/test-report.xml"
        displayName: 'Run tests'  
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-report.xml'
          testRunTitle: 'Test results'  
      - script: npm run prettier:check
        displayName: Syntax check
      - script: npm run extension:version:set
        displayName: Set release version
        condition: eq(variables['release'], 'true')
      - script: npm run extension:create:dev
        displayName: Build extension